net.Receive( "devbanlogssvr", function()
	local banlinfo = net.ReadTable()
	local steamids = net.ReadString()
	BackgroundCheck(banlinfo,steamids)
end)
--concommand.Add("banlogs", function() 
--	net.Start("devbanlogscl")
--	net.SendToServer()
--end)

local function BackgroundCheck(baninfo,steamid)
	local tbltoprint = table.KeysFromValue(baninfo,steamid)
	local tableintxt = table.ToString(tbltoprint,"Previous Offences",true)
	local Frame = vgui.Create( "DFrame" )
	Frame:SetPos( 5, 5 )
	Frame:SetSize( 600, 600 )
	Frame:SetTitle( "Previous Offences" )
	Frame:SetVisible( true )
	Frame:SetDraggable( true )
	Frame:ShowCloseButton( true )
	Frame:MakePopup()
		local DLabel = vgui.Create( "DLabel", Frame )
		DLabel:SetText( tableintxt )
		DLabel:SetPos( 5,5 )
		DLabel:SetDark( 1 )
		DLabel:SizeToContents()
end
